"""empty message

Revision ID: 472ba4d0da07
Revises: 7a20bf4ac0c0
Create Date: 2016-04-06 17:16:32.979831

"""

# revision identifiers, used by Alembic.
revision = '472ba4d0da07'
down_revision = '7a20bf4ac0c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
