"""empty message

Revision ID: 7a20bf4ac0c0
Revises: 8f3ad580c5f7
Create Date: 2016-04-06 17:16:24.282066

"""

# revision identifiers, used by Alembic.
revision = '7a20bf4ac0c0'
down_revision = '8f3ad580c5f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
