"""empty message

Revision ID: 8f3ad580c5f7
Revises: d727edac1ce5
Create Date: 2016-04-06 16:56:47.699450

"""

# revision identifiers, used by Alembic.
revision = '8f3ad580c5f7'
down_revision = 'd727edac1ce5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('myprofile', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('myprofile', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_myprofile_email'), 'myprofile', ['email'], unique=True)
    op.drop_column('myprofile', 'first_name')
    op.drop_column('myprofile', 'last_name')
    op.drop_column('myprofile', 'high_score')
    op.drop_column('myprofile', 'image')
    op.drop_column('myprofile', 'sex')
    op.drop_column('myprofile', 'tdollars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('tdollars', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('sex', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('image', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('high_score', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_myprofile_email'), table_name='myprofile')
    op.drop_column('myprofile', 'password')
    op.drop_column('myprofile', 'name')
    op.drop_column('myprofile', 'email')
    ### end Alembic commands ###
