"""empty message

Revision ID: a4bf906fb441
Revises: c954e54976c7
Create Date: 2016-04-20 19:33:36.121029

"""

# revision identifiers, used by Alembic.
revision = 'a4bf906fb441'
down_revision = 'c954e54976c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
