"""empty message

Revision ID: b549aa21cc18
Revises: 472ba4d0da07
Create Date: 2016-04-06 18:42:32.419644

"""

# revision identifiers, used by Alembic.
revision = 'b549aa21cc18'
down_revision = '472ba4d0da07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myprofile', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myprofile', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
