"""empty message

Revision ID: c954e54976c7
Revises: d02fad375638
Create Date: 2016-04-20 19:33:11.899089

"""

# revision identifiers, used by Alembic.
revision = 'c954e54976c7'
down_revision = 'd02fad375638'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
