"""empty message

Revision ID: d02fad375638
Revises: 3af1f440975b
Create Date: 2016-04-06 22:10:18.476956

"""

# revision identifiers, used by Alembic.
revision = 'd02fad375638'
down_revision = '3af1f440975b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
