"""empty message

Revision ID: d727edac1ce5
Revises: 62182ebcba65
Create Date: 2016-04-05 01:39:57.190622

"""

# revision identifiers, used by Alembic.
revision = 'd727edac1ce5'
down_revision = '62182ebcba65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
